import { ShiftReport } from "@/components/shift-reports/ShiftReport";

export default function ShiftReportsPage() {
  return (
    <div>
      <h1 className="mb-1 font-display text-2xl font-bold">Shift Reports</h1>
      <p className="mb-6 text-sm text-txt2">
        Autonomous executive handover reports generated by the Report Generation agent.
      </p>
      {/* Server component */}
      {/* @ts-expect-error Async Server Component */}
      <ShiftReport shiftId="shift-demo" />
    </div>
  );
}
